#!/bin/bash

### Set default parameters
action=$1
domain=$2
owner=$(who am i | awk '{print $1}')
sitesEnable='/etc/apache2/sites-enabled/'
sitesAvailable='/etc/apache2/sites-available/'
fextension='.conf'
userDir=$(eval echo ~${SUDO_USER})'/public_html/'

if [ "$(whoami)" != 'root' ]; then
        echo "You have no permission to run $0 as non-root user. Use sudo !!!"
        exit 1;
fi

if [ "$action" != 'create' ] && [ "$action" != 'delete' ]
	then
		echo "You need to prompt for action (create or delete) -- Lower-case only !!!!!!"
	    exit 1;
fi

while [ "$domain" == ""  ]
do
	echo -e "Please provide domain. e.g.dev,staging"
	read  domain
done

rootdir=${domain//./}

if [ "$action" == 'create' ]
	then
		### check if domain already exists
		if [ -e $sitesAvailable$domain$fextension ]; then
			echo -e 'This domain already exists.\nPlease Try Another one'
			exit;
		fi

		### check if directory exists or not
		if [ -d $userDir$rootdir ]; then
			echo -e 'Directory already exists !'
			exit;
		fi

		### create the directory
		mkdir $userDir$rootdir

		### create virtual host rules file
		if ! echo "<VirtualHost *:80>
	ServerName $domain
	ServerAlias www.$domain
	DocumentRoot $userDir$rootdir
	<Directory />
		AllowOverride All
	</Directory>
	<Directory $rootdir>
		AllowOverride All
	</Directory>
	ErrorLog /var/log/apache2/$domain
	LogLevel error
	CustomLog /var/log/apache2/$domain custom
</VirtualHost>" > $sitesAvailable$domain$fextension
		then
			echo -e '[ERROR] Unable to create vhost config file.'
			exit;
		else
			echo -e '[INFO] Virtual host config created.'
		fi

		### Add domain in /etc/hosts
		if ! echo "127.0.0.1       $domain" >> /etc/hosts
		then
		    echo "[ERROR] Unable to write to /etc/hosts"
		    exit;
		else
		    echo -e "[INFO] Host added to /etc/hosts file."
		fi

		### enable website
		a2ensite $domain

		### restart Apache
		service apache2 restart

		### give permission to root dir
		chmod 755 $userDir$rootdir

		### write test file in the new domain dir
		if ! echo "<?php echo phpinfo(); ?>" > $userDir$rootdir/phpinfo.php
		then
		    echo "[ERROR] Unable to write in file "$userDir"/"$rootdir"/phpinfo.php. Please check permissions."
		    exit;
		else
		    echo "[INFO] Added content to "$userDir$rootdir"/phpinfo.php."
		fi

		if [ "$owner" == ""  ]; then
			chown -R $(whoami):$(whoami) $userDir$rootdir
		else
			chown -R $owner:$owner $userDir$rootdir
		fi

		### show the finished message
		echo -e "[SUCCESS] Complete. New host: http://"$domain", Location: "$userDir$rootdir
		exit;
	else
		### check whether domain exists
		if ! [ -e $sitesAvailable$domain$fextension ]; then
			echo -e '[ERROR] Domain did not exist.'
			exit;
		fi

		### check if directory exists or not
		if ! [ -d $userDir$rootdir ]; then
      ### Delete the directory
      rm -rf $userDir$rootdir
    else
      echo -e '[WARNING] Directory did not exist'
		fi

		### Delete virtual host rules file
		rm $sitesAvailable$domain$fextension

		### Delete domain in /etc/hosts
		newhost=${domain//./\\.}
		sed -i "/$newhost/d" /etc/hosts

		### disable website
		a2dissite $domain

		### restart Apache
		service apache2 restart

		### show the finished message
		echo -e "[SUCCESS] Complete. Removed virtual host "$domain
		exit 0;
fi
